#!/bin/bash

ver=1.0

#//////////////// Defining default variables/////////////////////

#Default que
qname="diskq"
QNAME=$qname
#maxtime is 15 days!
maxtime=3-00:00:00
MAXTIME=$maxtime
#default memory is 16 GB
defm=16000
MEM=$defm
Node=1
#defalut tasks per node
tpn=2
TPN=$tpn
JOBNAME="file"
# By Default the current directory will be chosen for input and output
OUTPUTDIR=`pwd`
INPUTDIR=`pwd`
SUBMIT=1
USER1=$(logname) #default e-mail address
#///////////////////////////////////////////end /////////////////////////////////
#commands for running quantics
cat <<EOF >$INPUTDIR/ComMands
quantics -mnd \$JOBNAME.inp
EOF

# Accessing the partition information of the cluster!
#////////////////////////////////////////////////////////////////////////////
#***************************************************************************
scontrol show partition > info.txt
#q_variables
x="1 2 3 4 5 6"
id=0;
for j in $x;
        do
        n[id]=$( cat info.txt |awk '/PartitionName/{i++}i=='$j'' | grep PartitionName | cut -d '=' -f 2);
        T[id]=$( cat info.txt |awk '/PartitionName/{i++}i=='$j''| grep MaxTime | cut -d '=' -f 3 | cut -d ' ' -f 1  )
        M[id]=$( cat info.txt |awk '/PartitionName/{i++}i=='$j''|grep Nodes| awk '/Nodes/{i++}i==3' | cut -d '=' -f 2  )
        CPUN[id]=$( cat info.txt |awk '/PartitionName/{i++}i=='$j''|grep CPU | awk '/Nodes/{i++}i==2' | cut -d '=' -f 3|cut -d ' ' -f 1 )
        N[id]=$( cat info.txt |awk '/PartitionName/{i++}i=='$j''|grep TotalNodes | cut -d '=' -f 4| cut -d ' ' -f 1)
        id=$((id+1))
done
rm info.txt
node=${N[3]}

# quotes
quotes[0]="As far as the laws of mathematics refer to reality,they are not certain,\n and as far as they are certain, they do not refer to reality \n-A.Einstien \n"
quotes[1]="In theory, there is no difference between theory and practice.\n But, in practice, there is \n -A.Einstien \n "

quotes[2]="Every attempt to employ mathematical methods in the study of chemical questions\n must be considered profoundly irrational and contrary to the spirit of chemistry. \n If mathematical analysis should ever hold a prominent place in chemistry \n- an aberration which is happily almost impossible - \nit would occasion a rapid and widespread degeneration of that science\n -A.Comte \n "
quotes[3]="If we knew what we were doing, it wouldn't be called research \n -A Einstien"
quotes[4]="Common sense is the collection of prejudices acquired by age eighteen \n - Albert Einstein"
quotes[5]="Anyone who is not shocked by quantum theory has not understood a single word.  \n Niels Bohr"
quotes[6]="It takes so long to train a physicist to the place where he understands \nthe nature of physical problems that he is already too old to solve them\nEugene Wigner"
quotes[7]="It takes so long to train a quantum chemist to the place where she understands the nature of chemical problems\n that she has already invested so much in a specific software package\n that it is easiest just to ignore them and proceed\n -Seth Olsen "
quotes[8]="I like pigs. Dogs look up to us. Cats look down. But Pigs treat us as Equals. \n Winston Churchill."
quotes[9]="I am not rich enough to buy cheap things \n saying from Britain"

#End of definitions
#********************************************************************************
#///////////////////////////////////////////////////////////////////////////////



usage () {
use="Usage of the script:-\n

      To run the command with default variables use, submit_quantics file.inp \n
or, to use a particular que, use submit_quantics file.inp qname  \n 
or to override the default variables use, submit_quantics file.inp qname [options] \n
To know more about the available options, type submit_quantics help \n"

echo -en  $use
}
default_var () {
deftext=" Default variables will be used :- \n
          qname=\t$qname \n
          mem=\t$defm MB\n
          tasks/node=\t 2 \n
          Outputdir=\t $OUTPUTDIR \n
          maxtime=\t $maxtime \n
          USER=\t $(logname)\n
          commands=\t quantics -mnd file \n
         \t           quantics -pes file \n
          Please note: The default values can be overridden with optional keywords.\n
          Type submit_quantics help for more details\n
          Have fun with Quantum dynamics! \n"
echo -en $deftext 
}
# To print some random quotes
prandq () {
rand=$[ $RANDOM % 9 ]
echo " **********************************************************************************"
echo -e ${quotes[$rand]}
echo "************************************************************************************"
}
# To print the qinfo
q_info () {
table=" \
  --------------------------------------------------------------\n 
  Que\t  ||\t MaxTime\t ||\t Memory\t ||\t MaxNodes\t || \n
  -------------------------------------------------------------\n
  ${n[0]} ||\t ${T[0]}\t ||\t ${M[0]}\t ||\t ${N[0]}\t || \n
  ${n[1]} ||\t ${T[1]}\t ||\t ${M[1]}\t ||\t ${N[1]}\t || \n
  ${n[2]} ||\t ${T[2]}\t ||\t ${M[2]}\t ||\t ${N[2]}\t || \n
  ${n[3]} ||\t ${T[3]}\t ||\t ${M[3]}\t ||\t ${N[3]}\t || \n
  ${n[4]} ||\t ${T[4]}\t ||\t ${M[4]}\t ||\t ${N[4]}\t || \n
  ${n[5]} ||\t ${T[5]}\t ||\t ${M[5]}\t ||\t ${N[5]}\t || \n
  "
echo -en $table | column  -t
}

# To print help

print_help () {
usage

HELP="\
      help\t prints help text\n
      ver/version/--v\t prints version of the submit script\n
      qinfo\t prints Que info \n
       default\t   print default variables\n
       Following are the [options] to override the default variables in the script \n
       Note : submit_quantics file.inp qname [options]\n
       The order of the arguments should be preserved while the order within the options doesnt matter\n
       n\t no.of nodes\n
       m\t override default memory with given memory (in MB)\n
       t\t override default-wall clock time (in hr:min:ss format)\n
       T\t change the default ntasks/node\n
       u\t   --specify just the user name (of rug email: job status sent here)\n
       i\t  --Specify explicit input directory\n
      o\t  --explicit output directory\n
      s\t --[0] create the job file only (will not submit the file)\n"
     echo -en "$HELP"
}

#If you want to add extra commands add after quantics -mnd line

#ake ComMands file
call_steno () {
Jobn=$JOBNAME
echo "#!/bin/bash" >${Jobn}.sh
echo " #SBATCH -p $QNAME
#SBATCH -N $node1 
#SBATCH --mem=$MEM1
#SBATCH --ntasks-per-node=$ntasks
#SBATCH --time=$MAXTIME1
#SBATCH --mail-user=$USER1
#SBATCH --mail-type=ALL
#SBATCH --kill-on-invalid-dep=yes
#SBATCH -o quanticsjob_%j.log
date;hostname;pwd
#This job is submited using submit_quantics-version-$ver.
module load openmpi/gcc/64/2.1.1
module add quantics/quantics
source $QUANTICS_DIR/install/QUANTICS_client
cd \$TMPDIR
mkdir $JOBNAME 
cd $JOBNAME 
#cp $INPUTDIR/$INPUT $JOBNAME/ ">>${Jobn}.sh
echo "cp $INPUTDIR/$JOBNAME.inp .">>${Jobn}.sh 
echo "quantics -mnd $JOBNAME.inp">>${Jobn}.sh
echo "date   ">>${Jobn}.sh
echo "cp -r $JOBNAME $OUTPUTDIR">>${Jobn}.sh
}

#Print Qerror if the variable chosen doesnt fit to the requested partition
qerr () {
qerror="The variables entered are exceeding the allowed parameters in the $QNAME que \n
        for more details, use qinfo command. ./submitjob qinfo \n "
echo -en "$qerror"

}
# Acknowledge the user about the updated variable
happy_note () {
happynote="I have taken the default parameters associated with the $QNAME. \n
To override the node -n and to override mem -m. Type, submit_quantics help or -h or ?  , for more detailed usage of options !\n"
echo -en ""$happynote""
}



# ///////////////////////end of functions/////////////////////////////////////////////

#If the number of arguments are less than 1


if [ $# -lt 1 ]; then
   echo 'Warning: Not enough arguments.'
    usage
    prandq
   exit
fi



#If the number if argument is just one!
if [ $# -eq 1  ]; then
        opt=$1
        if [[ $opt == *.inp ]]; then
                if [ -f $INPUTDIR/$opt ]; then
                   INPUT=$opt
                   JOBNAME=$(basename "$opt" .inp)
                   echo " The job name is $JOBNAME"
                          node1=$Node
			   MEM1=$MEM
                          MAXTIME1=$MAXTIME
                          ntasks=$tpn
                          echo $JOBNAME
                          SUBMIT=1
                          echo "The job will be submited in the $QNAME"
                         prandq
                 else
                    echo "The file doesnt exist in $INPUTDIR .  please run from the directory of your input file"
                           prandq
                           exit
                  fi
        else
                case $opt in
                qinfo) #qinfo 
                       q_info;;
                default) #default_variables
                        default_var;;
        --v|-version|-ver) # print the version of submit script
                          echo "The version of the script you are using is submit_quantics-version-$ver";;
               ?| -h| help)
                       print_help;;
                    *)
                       echo "unrecogonized command"
                       print_help
                        prandq;;
                   esac
		SUBMIT=-1
                fi
 fi

# if the input has more than one argument.. 

# The first argument should be file.inp and the second argument should be qname , followed by optional arguments!

if [ $# -ge 2 ] ; then
        input=$1
        echo $input
        if [[ $input == *.inp ]]; then
                if [ -f "$INPUTDIR"/"$input" ]; then
                   INPUT=$input
                   JOBNAME=$(basename "$input" .inp)
                   MEM1=$defm
                   MAXTIME1=$MAXTIME
                   echo " The job-file named is $JOBNAME.sh is created"
                 else
                    echo " The file doesn't exist in $INPUTDIR ! please run from the directory of your input file."
                           exit 
                 fi
        fi

        shift 1
         case $1 in
                       defq)
                                echo " default que is chosen , the maxtime is ${T[0]} (maxtime will be set unless specified) and memory available is ${M[0]}"
                                echo " Available processors in the node are : ${CPUN[0]} default memory is $defm MB"
                                QNAME="defq"
				MAXTIME=${T[0]}
                                MAXTIME=$(echo ${T[5]} | cut -d'-' -f 1 )
                                MAXTIME=$(( $MAXTIME * 24 ))
                                MAXTIME="$MAXTIME:00:00"
                                MAXTIME1=$MAXTIME
                                MEM1=$defm
                                nodes=${N[0]}
                                ntasks=2
                                happy_note
                                break;;
                        gpuq) #gpuq
                                echo " GPU que is chosen , the maxtime is ${T[1]} (default-time will be set unless specified) and memory available is ${M[1]}"
                                echo " Available processors in the node are : ${CPUN[0]} default memory is $defm MB"
                                echo " Be informed that to use this node Quantics should be GPU-compatible, Ethical issues!"
                                QNAME="gpuq"
				MAXTIME=$deft
                                MAXTIME=$(echo $deft | cut -d'-' -f 1 )
                                MAXTIME=$(( $MAXTIME * 24 ))
                                MAXTIME="$MAXTIME:00:00"
                                MAXTIME1=$MAXTIME
                                MEM1=$defm
                                nodes=${N[1]}
                                ntasks=2
                                happy_note
                                break;;
                        diskq) echo " Lowest processor que is chosen , the maxtime is ${T[2]} (default-time will be set unless specified) and memory available is ${M[2]}"
                                echo " Available processors in the node are : ${CPUN[2]} default memory is $defm MB"
                                MAXTIME=$deft
                                MEM1=$defm
                                MAXTIME=$(echo $deft | cut -d'-' -f 1 )
                                MAXTIME=$(( $MAXTIME * 24 ))
                                MAXTIME="$MAXTIME:00:00"
                                nodes=${N[2]}
                                MAXTIME1=$MAXTIME
                                ntasks=2
				QNAME="diskq"
                                happy_note
                                break;;
                        memq)   QNAME="memq"
                                echo " High memory que is chosen , the maxtime is ${T[3]} (default-time will be set unless specified) and memory available is ${M[3]}"
                                echo " Available processors in the node are : ${CPUN[3]} default memory is $defm MB"
                                MAXTIME=$deft
                                MAXTIME=$(echo $deft | cut -d'-' -f 1 )
                                MAXTIME=$(( $MAXTIME * 24 ))
                                MAXTIME="$MAXTIME:00:00"
                                MAXTIME1=$MAXTIME
                                MEM1=$defm
                                nodes=${N[3]}
                                ntasks=2
                                happy_note
                                break;;
                         shortq)QNAME="shortq"
				echo " High memory que is chosen , the maxtime is ${T[4]} (default-time will be set unless specified) and memory available is ${M[4]}"
                                echo " Available processors in the node are : ${CPUN[4]} default memory is $defm MB"
                                MAXTIME=${T[4]}
                                MAXTIME=$(echo ${T[4]} | cut -d'-' -f 1 )
                                MAXTIME=$(( $MAXTIME * 24 ))
                                MAXTIME="$MAXTIME:00:00"
                                MAXTIME1=$MAXTIME
                                MEM1=$defm
                                nodes=${N[4]}
                                ntasks=2
                                happy_note
                                break;;

                         ultrashortq)QNAME="ultrashortq"
                                echo " Ultrashort que is chosen , the maxtime is ${T[5]} (maxtime will be set unless specified) and memory available is ${M[5]}"
                                echo " Available processors in the node are : ${CPUN[5]} default memory is $defm MB"
                                MAXTIME=${T[5]}
                                MAXTIME=$(echo ${T[5]} | cut -d'-' -f 1 )
                                MAXTIME=$(( $MAXTIME * 24 ))
                                MAXTIME="$MAXTIME:00:00"
                                MAXTIME1=$MAXTIME
                                MEM=$defm
                                MEM1=$MEM
                                nodes=${N[5]}
                                ntasks=2
                                happy_note
                                ;;
                            *)
                                echo "Unrecogonizable que name"
                                echo -en  $table | column  -t
                                exit;;
                        esac
                       shift 1

              options=$1
	      while getopts ":n:m:T:u:t:i:o:s:c:h:" options ; do
                      case $options in
				 n)  #no of nodes
                                       nod=${OPTARG}
                                       if [[ $nod -lt $nodes ]]; then
                                       node1=$nod
                                       echo " I have taken node , $node1 :) "
                                       else
                                       node1=$nodes
                                       qerr
                                        fi
                                       ;;
                                   m) #Memory required
                                      echo" I reached here"
                                      mem=${OPTARG}
                                      if [[ $mem -lt $defm ]]; then
                                      MEM1=$mem
                                      echo "Memory is updated as $mem" 
                                      else
                                        MEM1=$defm
                                        qerr
                                        echo "Retained the default memory"
                                      fi
                                      ;;
                                    T)
                                        nts=${OPTARG}
                                        if [ $nts -eq 1 ]; then
                                              ntask1=$nts
                                              echo "ntasks/node is modified as $nts" 
                                         else
                                              ntask1=$ntasks
                                              echo "ntasks per node can only be one or two while two is default" 
                                         fi
                                        ;;

                                 u)
                                    usr=${OPTARG}
                                    mail="@rug.nl"
                                    USER1=$usr$mail
                                    echo "Gotcha, $usr ;)"
                                    echo "Hey Groninger! Your job related email would be sent to $USER1"
                                    ;;
                                  t)
                                     maxt=${OPTARG}
                                    # Days obtained from the user
                                    newt=$(echo $maxt | cut -d ':' -f 1)
				    # Default days from the MAXTIME
                                    defd=$(echo $MAXTIME | cut -d ':' -f 1)
                                    mins=$(echo $MAXTIME | cut -d ':' -f 2)
                                    secs=$(echo $MAXTIME | cut -d ':' -f 3)
                                    min=$(echo $maxt | cut -d ':' -f 2)
                                    sec=$(echo $maxt | cut -d ':' -f 3)
                                    if [[ $newt -lt $defd ]]; then           
                                          MAXTIME1=$maxt
                                          echo "Wall-clock time adjusted to $maxt"
                                    elif [[ $newt -eq $defd ]]; then
                                           MAXTIME1="$newt:00:00"
                                           echo "Maximum wall-clock time reached. Hence,minutes and seconds are retained as zero"
                                           echo "Your modified wall-clock time is $MAXTIME1" 
				    else
					  MAXTIME1=$MAXTIME
                                          echo "The time given in hr:min:sec exceeded the MAXTIME permissible under the partition!"
                                          qerr
                                          exit 

              	                    fi
                                    ;;
                                   i) inputdir=${OPTARG}
                                      if [ -d "$inputdir" ]; then
                                      	INPUTDIR=$inputdir
                                        path=`pwd`
					echo "Caution: Your current path is $path and the requested Working directory is $INPUTDIR "
                                      else
                                          INPUTDIR=`pwd`
                                      fi
                                     ;;
				o) outputdir=${OPTARG}
                                      if [ -d "$outputdir" ]; then
                                        OUTPUTDIR=$outputdir
                                        path=`pwd`
                                        echo "Caution: The default output directory is $path and the requested output directory is $OUTPUTDIR "
                                      else
                                          OUTPUTDIR=`pwd`
                                      fi
                                     ;;

                                  s)
                                      sub=${OPTARG}
                                       if [ $sub -gt 0 ];  then
                                            SUBMIT=1
                                       else
                                             SUBMIT=0
                                        fi
                                       ;;
				   c)
                                      comfile=${OPTARG}
                                      mv $comfile ComMands
                                      ;;
                                   h|*)
                              		echo "Unrecognized option" >&2
                              		#Print help
                                        print_help
                                        exit
                                        ;;
                                     esac
                         done
                         shift $(( OPTIND - 1 ))
fi
node1=$node ;
if [[ $SUBMIT == 1 ]]; then
	call_steno
	echo "Job will be submitted in $QNAME"
        sbatch ${Jobn}.sh 
        date 
        prandq
elif [[ $SUBMIT -lt 0 ]]; then
	exit
 
else
	call_steno
        echo " Warning ! The job file called ${Jobn}.sh is created and its not submitted"
        prandq
        exit
 
fi


